// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flgame/models/lgame_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GamePlayerTurnAdapter());
    registerAdapter(HiveLGameSessionDataAdapter());
    registerAdapter(LGamePieceInMoveAdapter());
    registerAdapter(LGameSessionDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GamePlayerTurnAdapter());
    registerAdapter(HiveLGameSessionDataAdapter());
    registerAdapter(LGamePieceInMoveAdapter());
    registerAdapter(LGameSessionDataAdapter());
  }
}
